### PR TITLE
Llmeval refactor

### PR DESCRIPTION
**Pull request by vnikouliNLE**
Refactored llmevaluator: it now depends from generator 
Extended llmeval with multiple options
- possibility to specify model to be used (by specifying the  name of the generator config file)
- extend beyond binary evalaution (via yaml configuration file, you can specify options and associated values)
-  updated readme accordingly
- added associated unit tests for llmeval
- updated LID calculation, added a possibilyt to getlng specification from config file

### CODE REVIEW

**Comment by DRRV** [comment]
What was the issue with the memory?

**Comment by sclincha** [comment]
-Issues like those one: https://discuss.pytorch.org/t/torch-pytest-leads-to-memory-fragmentation-how-to-do-proper-integration-testing-of-a-lot-of-torch-models/201231
- The issue is with VLLM as evaluator. If we add that test, it breaks. If we run the test independantly (pytest tests/ -k TestBergenEval pytest tests -k TestBergenMain), it runs fine

**Comment by DRRV** [comment]
by modifying the gpu_memory_utilization  parameter when creating the vLLM object  tests are ok ( both Main and eval)
But I get: 
E                       ImportError: Error loading 'modules.dataset_processor.KILTNQ':
E                       ModuleNotFoundError("No module named 'modules.dataset_processor.KILTNQ'; 'modules.dataset_processor' is not a package")
E                       Are you sure that 'KILTNQ' is importable from module 'modules.dataset_processor'?

**Review by DRRV — APPROVED** [review]

**Comment by nadiinchi** [comment]
Comments on LID implementation, https://github.com/naver/bergen/blob/llmeval_refactor/models/evaluators/lid.py:
* line 39: should be `return -1`? to implement skipping the item
* same file, `correct_lang` does not seem to be using `self.model` at all? -> suggestion to add it as a third ensembled model
* I am not sure about using gold answer's language as an allowed target (line 34), because gold answers are sometimes in English (it's eval data issue)... but it's rare so maybe it's fine
* remove `print`s used for debugging

**Comment by DRRV** [comment]
I'm always getting weird=100%
len(possible_scores)>1   should be  len(possible_scores **[i]** )>1 ?  (seems to work with bs=1)

**Comment by DRRV** [comment]
the current main/eval  is a bit buggy so @vnikouliNLE I think you can merge.  I've tested the last commits.

**Comment by DRRV** [comment]
@vnikouliNLE I did some stupid things with one of my commits (pushed too many things). I will clean it up

**Pull request merged**
